name: Sample
on:
  workflow_dispatch:
concurrency:
  group: sample
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sleep 30 seconds
        run: |
          echo start!
          sleep 30
          echo finished!
